mirror-main:
  stage: mirror
  variables:
    UPSTREAM_REPOSITORY: "git@github.com:immelstorun/datascience-pro-cookiecutter.git"
    UPSTREAM_BRANCH: "main"
    GIT_SUBMODULE_STRATEGY: none
    GIT_STRATEGY: clone
  cache: {}
  only:
    - main
  script:
    - mkdir -p ~/.ssh                                                  # 1
    - echo $GITHUB_MIRROR_PRIVATE | base64 -d > ~/.ssh/id_rsa          # 2
    - echo $GITHUB_MIRROR_PUBLIC > ~/.ssh/id_rsa.pub                   # 3
    - ssh-keyscan -t rsa,dsa,ecdsa github.com >> ~/.ssh/known_hosts    # 4
    - chmod -R go-rwx ~/.ssh                                           # 5
    - git remote add mirror $UPSTREAM_REPOSITORY                       # 6
    - git remote show mirror                                           # 7
    - git fetch mirror                                                 # 8
    - git push --progress mirror HEAD:main                             # 9
