stages:
  - sync

variables:
  GITHUB_REPO: "https://immelstorun:${GITHUB_PAT}@github.com/immelstorun/datascience-pro-cookiecutter.git"
  GIT_DEPTH: 1  # Чтобы ускорить процесс, можно ограничить глубину истории

sync_to_github:
  stage: sync
  script:
    # Клонируем репозиторий GitLab
    - git clone --depth $GIT_DEPTH https://gitlab.cspfmba.ru/aseikin/datascience-pro-cookiecutter.git repo
    - cd repo
    # Устанавливаем настройки Git, чтобы избежать проблем с аутентификацией
    - git config user.email "ci@example.com"
    - git config user.name "CI/CD"
    # Добавляем GitHub как удалённый репозиторий
    - git remote add github $GITHUB_REPO
    # Пушим изменения в GitHub
    - git push github --all
    - git push github --tags
  only:
    - main  # Или ветка, которую хотите зеркалировать
