stages:
  - sync

sync_with_github:
  stage: sync
  before_script:
    - eval "$(ssh-agent -s)"
    - ssh-add /home/gitlab-runner/.ssh/id_ed25519
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - ls -l /home/gitlab-runner/.ssh/  # Выводим содержимое директории с ключами
    - ssh -T git@github.com  # Проверка подключения

  script:
    - git push --mirror git@github.com:immelstorun/datascience-pro-cookiecutter.git
  only:
    - main  # Запускать только при коммитах в main




# stages:
#   - test

# test_job:
#   stage: test
#   script:
#     - echo "Hello, GitLab Runner!"

# stages:
#   - sync

# sync_to_github:
#   stage: sync
#   script:
#     - git config --global user.name "GitLab CI"
#     - git config --global user.email "gitlab-ci@example.com"
#     # Клонируем репозиторий с GitLab
#     - git clone https://gitlab.cspfmba.ru/aseikin/datascience-pro-cookiecutter.git
#     - cd datascience-pro-cookiecutter
#     # Добавляем удалённый репозиторий GitHub с использованием токена
#     - git remote add github https://$GITHUB_TOKEN@github.com/immelstorun/datascience-pro-cookiecutter.git
#     # Проверяем и пуллим последние изменения с GitHub
#     - git fetch github
#     - git merge github/main --strategy-option=theirs || echo "No changes to merge"
#     # Пушим изменения в GitHub
#     - git push github main
#   only:
#     - main


